### ISSUE TITLE
After Upgrade to 6.1.5 many errors in Log and Adapter not starting

### ISSUE THREAD

**Issue by SKB-CGN** [Grizzelbee/ioBroker.mielecloudservice#239] opened 2022-05-09 08:12 UTC
Hi,
the Adapter does not start anymore.

Following errors in Log:

`<html><body>

host.ioBroker | 2022-05-09 10:11:39.856 | warn | Do not restart adapter system.adapter.mielecloudservice.0 because restart loop detected
-- | -- | -- | --
host.ioBroker | 2022-05-09 10:11:39.855 | info | Restart adapter system.adapter.mielecloudservice.0 because enabled
host.ioBroker | 2022-05-09 10:11:39.854 | error | instance system.adapter.mielecloudservice.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
host.ioBroker | 2022-05-09 10:11:39.854 | error | Caught by controller[1]:     at /opt/iobroker/node_modules/iobroker.mielecloudservice/source/mieleTools.js:92:22
host.ioBroker | 2022-05-09 10:11:39.853 | error | Caught by controller[1]:     at processTicksAndRejections (internal/process/task_queues.js:95:5)
host.ioBroker | 2022-05-09 10:11:39.853 | error | Caught by controller[1]:     at /opt/iobroker/node_modules/iobroker.mielecloudservice/source/mieleTools.js:127:32
host.ioBroker | 2022-05-09 10:11:39.852 | error | Caught by controller[1]: TypeError: Cannot read property 'status' of undefined
host.ioBroker | 2022-05-09 10:11:39.852 | error | Caught  by controller[0]: This error originated either by throwing inside of an  async function without a catch block, or by rejecting a promise which  was not handled with .catch(). The promise rejected with the reason:
mielecloudservice.0 | 2022-05-09 10:11:39.279 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason

</body>
</html>`

**Comment by Grizzelbee** [comment] 2022-05-09 15:53
closed due to duplicate of #238 
please report any news there.

**Closed by Grizzelbee** 2022-05-09 15:53 UTC
Labels: duplicate
