### ISSUE TITLE
Client network socket disconnected before secure TLS connection was established

### ISSUE THREAD

**Issue by Goersch** [Grizzelbee/ioBroker.mielecloudservice#238] opened 2022-05-08 15:36 UTC
iobroker always disables adapter because of too many restarts. Log of adapter
![logs - HA-Server](https://user-images.githubusercontent.com/24088528/167303685-f0967b56-d16d-4e54-a0f3-7125efaff069.png)

**Comment by Pnuts76** [comment] 2022-05-08 18:08
I also have issues with version 6.1.5 of mielecloudservice adapter and adapter is restarted a lot of time until iobroker completly stops adapter after too many restarts.
The adapter also produces a lot of DNS request for 'api.mcs3.miele.com' so that after a certain time, my pihole begins to reject DNS requests from iobroker for this address.
I attached an excerpt of iobroker logfile regarding the mielecloudservice messages. I hope this helps to find the root cause.
[mielecloudservice.log](https://github.com/Grizzelbee/ioBroker.mielecloudservice/files/8647507/mielecloudservice.log)

**Comment by Grizzelbee** [comment] 2022-05-09 15:58
facing this issue myself too. trying to find a solution.

**Comment by Grizzelbee** [comment] 2022-05-12 11:29
@Pnuts76 
Just long term testing V6.2.0 in my productive environment. This version got some improvements and I hope to solve most issues with this release.
Please test this version as soon as it is released in the latest branch and report if it works for you or not. 
Especially I am interested in the many DNS requests reported by you since I really expect only a few to occur. DNS requests should only occur:
* on adapter startup
* when a device gets powered on
* on adapter shutdown

In the meantime the API Server keeps the connection alive and I don't expect any DNS requests during this time.

**Comment by Pnuts76** [comment] 2022-05-12 11:36
@Grizzelbee 
I will deploy and test the latest version as soon as it is available.
I will also have an eye on DNS requests and give you feedback afterwards.
Thank you for your efforts.

**Comment by Grizzelbee** [comment] 2022-05-12 13:42
Hmmm. Just read the issue again and took a deeper look into your screenshot...
It may be that the PiHole is causing your issues. I read a few times something about "wrong proxy setup in connection request", when googleing the different error messages that we are facing. They were telling to include the proxy in the request options. So it may be that v6.2.0 won't solve your issue (by using SSE) and I need to add a proxy config to the admin page - but this is just thinking loudly. If SSE won't work for you - I reintroduce data polling again.

**Comment by Pnuts76** [comment] 2022-05-12 14:00
Did you mean the errors in the logs I attached...? Errors from screenshot are from another user.
I guess, we shoud not have a problem with SSE in combination with pihole, as pihole is just answering the local DNS requests and is not proxying any network traffic in my setup. I suggest to give it a try anyway.

**Comment by Grizzelbee** [comment] 2022-05-16 09:06
Great! On my side 6.2.0 runs pretty stable for three days now. Just logging one error message a day which all solved themself.

**Closed** 2022-05-19 05:12 UTC
Labels: bug, Fixed

**Comment by Pnuts76** [comment] 2022-05-19 07:30
Just wanted to confirm, that versions >= 6.2 are running fine in my environment. Thank you for your great work!

**Comment by Grizzelbee** [comment] 2022-05-19 09:05
@Pnuts76 

thanks for your confirmation and your warm words.
